// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "../cpp/header/error_code.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ErrorCode final : ::djinni::JniEnum {
public:
    using CppType = ::textsort::error_code;
    using JniType = jobject;

    using Boxed = ErrorCode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<ErrorCode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<ErrorCode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    ErrorCode() : JniEnum("io/ioprint/core/ErrorCode") {}
    friend ::djinni::JniClass<ErrorCode>;
};

}  // namespace djinni_generated
