// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "../cpp/header/item_list.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ItemList final {
public:
    using CppType = ::textsort::ItemList;
    using JniType = jobject;

    using Boxed = ItemList;

    ~ItemList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    ItemList();
    friend ::djinni::JniClass<ItemList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/ioprint/core/ItemList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mItems { ::djinni::jniGetFieldID(clazz.get(), "mItems", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
