// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "sort_items.hpp"  // my header
#include "item_list.hpp"
#include "sort_order.hpp"
#include "textbox_listener.hpp"

namespace djinni_generated {

SortItems::SortItems() : ::djinni::JniInterface<::textsort::SortItems, SortItems>("io/ioprint/core/SortItems$CppProxy") {}

SortItems::~SortItems() = default;


CJNIEXPORT void JNICALL Java_io_ioprint_core_SortItems_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::textsort::SortItems>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_io_ioprint_core_SortItems_00024CppProxy_native_1sort(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_order, jobject j_items)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::textsort::SortItems>(nativeRef);
        ref->sort(::djinni_generated::SortOrder::toCpp(jniEnv, j_order),
                  ::djinni_generated::ItemList::toCpp(jniEnv, j_items));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_io_ioprint_core_SortItems_00024CppProxy_createWithListener(JNIEnv* jniEnv, jobject /*this*/, jobject j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::textsort::SortItems::create_with_listener(::djinni_generated::TextboxListener::toCpp(jniEnv, j_listener));
        return ::djinni::release(::djinni_generated::SortItems::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
