// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "../cpp/gen/sort_order.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class SortOrder final : ::djinni::JniEnum {
public:
    using CppType = ::textsort::sort_order;
    using JniType = jobject;

    using Boxed = SortOrder;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<SortOrder>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<SortOrder>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    SortOrder() : JniEnum("io/ioprint/core/SortOrder") {}
    friend ::djinni::JniClass<SortOrder>;
};

}  // namespace djinni_generated
