// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "../cpp/header/sort_items.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class SortItems final : ::djinni::JniInterface<::textsort::SortItems, SortItems> {
public:
    using CppType = std::shared_ptr<::textsort::SortItems>;
    using CppOptType = std::shared_ptr<::textsort::SortItems>;
    using JniType = jobject;

    using Boxed = SortItems;

    ~SortItems();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<SortItems>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<SortItems>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    SortItems();
    friend ::djinni::JniClass<SortItems>;
    friend ::djinni::JniInterface<::textsort::SortItems, SortItems>;

};

}  // namespace djinni_generated
