// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace textsort {

enum class error_code : int {
    SUCCESS,
    ERROR,
};

}  // namespace textsort

namespace std {

template <>
struct hash<::textsort::error_code> {
    size_t operator()(::textsort::error_code type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
