// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

namespace textsort {

enum class error_code;
struct ItemList;

class TextboxListener {
public:
    virtual ~TextboxListener() {}

    virtual void update(error_code error_code, const ItemList & items) = 0;
};

}  // namespace textsort
